services:
  db:
    image: postgres:16
    container_name: education_doorway_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: doorway
      POSTGRES_PASSWORD: doorway
      POSTGRES_DB: education_doorway
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
